run:
  go: '1.20'
  timeout: 5m
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  revive:
    rules:
      - name: var-naming

issues:
  exclude-use-default: false
  exclude-files:
    - ".*_test.go"
  exclude-dirs:
    - vendor
    - examples  
output:
  formats: colored-line-number
